workers: 6
weight_decay: 0.0001
momentum: 0.9
display: 50
max_iter: 15000
batch_size: 64
test_interval: 1000
topk: 3
base_lr: 0.001
#-------------lr_policy--------------------#
# step
lr_policy: 'step'
policy_parameter:
  gamma: 0.1
  step_size: 5000
# exp
# lr_policy: 'exp'
# gamma: 0.99
# 
# inv
# lr_policy: 'inv'
# gamma: 0.1
# power: 0.1
# 
# multistep
# lr_policy: 'multistep'
# stepvalue: [5000, 8000, 10000]
# gamma: 0.1
# 
# poly
# lr_policy: 'poly'
# power: 0.9
# 
# sigmoid
# lr_policy: 'sigmoid'
# gamma: 0.9
# stepsize: 5000
