set number
set cursorline
set tabstop=2
set hlsearch
set autoindent
set mouse=a
set backspace=2
set smartindent
set ai!
set cindent shiftwidth=2
set viminfo='1000,<800

syntax on
set t_Co=256
colorscheme molokai

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'scrooloose/nerdcommenter'
Plugin 'Valloric/YouCompleteMe'
let g:ycm_global_ycm_extra_conf = '/home/hypan/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
let g:ycm_min_num_of_chars_for_completion = 2
let g:ycm_seed_identifiers_with_syntax = 1
let g:ycm_complete_in_comments = 1
let g:ycm_complete_in_strings = 1
let g:ycm_python_binary_path='/usr/bin/python3'

Plugin 'scrooloose/nerdtree'
let g:NERDTreeWinPos='left'
let g:NERDTreeWinSize=30
map <F2> :NERDTreeToggle<CR>
Plugin 'bling/vim-airline'
set laststatus=2
Plugin 'tomasr/molokai'
let g:molokai_original = 1
let g:rehash256 = 1
Plugin 'flazz/vim-colorschemes'
Plugin 'Yggdroot/indentLine'
let g:indentLine_char = '|'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

map <F3> :set paste<CR>
map <F4> :set nopaste<CR>
if has("autocmd")
	au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
